### PR TITLE
add package support

### PR DESCRIPTION
**Pull request by zapion**
- Add package support for mozMinions
- Add console command minions_run to invoke boss.main()

### CODE REVIEW

**Comment by zapion** [comment]
@ypwalter , @ShakoHo  r?

**Comment by ShakoHo** [comment]
downloaded and verified in my local env...r+

**Comment by ypwalter** [comment]
r-
the entry should be able to run else where instead of only running in the repository root folder?
Also, can you explain the reason of 7ed3caf6.json existence? In that case, I can better understand the program and code. Thanks.

```
(.env)wachen@WalterDesktop:~$ minions_run 
Traceback (most recent call last):
  File "/home/wachen/FirefoxOS/mozMinions/.env/bin/minions_run", line 9, in <module>
    load_entry_point('moz-minions==0.1.0', 'console_scripts', 'minions_run')()
  File "/home/wachen/FirefoxOS/mozMinions/.env/local/lib/python2.7/site-packages/moz_minions-0.1.0-py2.7.egg/moz_minions/boss.py", line 99, in main
    b.load('./conf/7ed3caf6.json')
  File "/home/wachen/FirefoxOS/mozMinions/.env/local/lib/python2.7/site-packages/moz_minions-0.1.0-py2.7.egg/moz_minions/boss.py", line 33, in load
    with open(fp) as in_data:
IOError: [Errno 2] No such file or directory: './conf/7ed3caf6.json'
```

**Comment by zapion** [comment]
I guess the bug was not related to this patch, but we will file an issue for this.

**Comment by ypwalter** [comment]
Okay, agreed.

```
(.env)wachen@WalterDesktop:~/FirefoxOS/mozMinions$ python moz_minions/boss.py 
Press Ctrl+C to exit
```

looks like it was a previous bug.
it's r+ then.
Thanks.

**Comment by zapion** [comment]
I commented hard coded path to prevent the error.
Will now working on load config mechanism.

**Comment by zapion** [comment]
Thanks for reviewing!

**Pull request merged**
